Add hw15
z-sector/otus-hw pull request #15
Opened 2023-07-30 18:01 UTC by z-sector

## Домашнее задание №15 «Докеризация и интеграционное тестирование Календаря»

### Критерии оценки
- [ ] Проект полностью запускается и останавливается с помощью `make up` / `make down` - 3 балла
- [ ] Интеграционные тесты запускаются с помощью `make integration-tests`. Команда возвращает верный код ответа - 1 балл

Интеграционные тесты покрывают бизнес сценарии:
- [ ] добавление события и обработка бизнес ошибок - 2 балла
- [ ] получение листинга событий на день/неделю/месяц - 2 балла
- [ ] отправка уведомлений - 2 балла

#### Зачёт от 7 баллов

2023-07-30 19:49 UTC, dshemin requested changes, later dismissed

2023-07-30 19:49 UTC, dshemin commented on hw12_13_14_15_calendar/Makefile
> +integration-tests:
Критично:

В тексте ТЗ сказано:

> У преподавателя должна быть возможность запустить весь проект с помощью команды
`make up` (внутри `docker-compose up`) и погасить с помощью `make down`.

2023-07-30 21:05 UTC, z-sector commented on hw12_13_14_15_calendar/Makefile
> +integration-tests:
DONE

2023-08-03 14:39 UTC, GeorgeRamaniuk approved these changes

2023-08-03 18:47 UTC, merged