Add hw04
z-sector/otus-hw pull request #4
Opened 2022-12-24 20:40 UTC by z-sector

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-12-24 23:18 UTC, Nikscorp approved these changes
Егор, добрый вечер!

Отличная работа, здорово, что решили реализовать на дженериках.
Оставил небольшие замечания к работе.

Работа принята.
Текущая оценка: 9 баллов

2022-12-24 23:18 UTC, Nikscorp commented on hw04_lru_cache/cache.go
> +		l.queue.Remove(item)
WARN: в этом случае эффективнее будет обновить значение в очереди и сделать `MoveToFront`, затем можно сразу `return ok`

2022-12-24 23:18 UTC, Nikscorp commented on hw04_lru_cache/cache.go
> +	if l.queue.Len() == l.capacity {
NB: все-таки наверное наглядней будет `l.queue.Len() > l.capacity` и переместить ее после push-a

2022-12-24 23:18 UTC, Nikscorp commented on hw04_lru_cache/list.go
> +	if i == nil || l.len == 0 {
NB: здесь и везде — обычно стараются избегать совместного использования переменных с именами `l` и `i`, так как их легко спутать

2022-12-24 23:18 UTC, Nikscorp commented on hw04_lru_cache/cache.go
> +type Cache[T any] interface {
NB: здорово, что сделали с generic-ами, в идеале тогда тип должен выглядеть как `Cache[K comparable, V any]`, часто в качестве ключа удобно использовать не только строки, но и структуры со сравниваемыми полями.

2022-12-24 23:18 UTC, Nikscorp commented on hw04_lru_cache/Makefile
> +	@go test -v -count=1
NB: `-race`

2022-12-25 11:17 UTC, z-sector commented on hw04_lru_cache/cache.go
> +		l.queue.Remove(item)
Исправил

2022-12-25 11:17 UTC, z-sector commented on hw04_lru_cache/cache.go
> +	if l.queue.Len() == l.capacity {
Исправил

2022-12-25 11:18 UTC, z-sector commented on hw04_lru_cache/list.go
> +	if i == nil || l.len == 0 {
Исправил

2022-12-25 11:18 UTC, z-sector commented on hw04_lru_cache/cache.go
> +type Cache[T any] interface {
Исправил

2022-12-25 11:18 UTC, z-sector commented on hw04_lru_cache/Makefile
> +	@go test -v -count=1
Добавил

2022-12-25 12:24 UTC, Nikscorp requested changes
Егор, добрый день. В решении появилась бага, исправьте пожалуйста.

2022-12-25 12:24 UTC, Nikscorp commented on hw04_lru_cache/cache.go
> +		l.queue.Remove(item)
CRIT: remove здесь лишний. Получается из очереди вы удалили, а в мапе оставили. Получается как минимум утечка памяти.
Достаточно просто сделать `MoveToFront`, после чего можно сразу делать `return ok`.

```go
	t.Run("some bug", func(t *testing.T) {
		c := NewCache[Key, int](2)

		c.Set("aaa", 100)
		// now aaa not in queue, so it won't be deleted from the map
		c.Set("aaa", 200)

		c.Set("bbb", 200)
		c.Set("ccc", 200)

		cs := c.(*lruCache[Key, int])
		require.Equal(t, 2, cs.queue.Len())

		// actual  : 3
		require.Equal(t, 2, len(cs.items))
	})
```

На это нужно добавить тест, возможно более осмысленный

2022-12-25 12:24 UTC, Nikscorp commented on hw04_lru_cache/cache.go
>  type Key string
NB: этот публичный тип теперь явно лишний

2022-12-25 12:50 UTC, z-sector commented on hw04_lru_cache/cache.go
>  type Key string
Удалил

2022-12-25 12:50 UTC, z-sector commented on hw04_lru_cache/cache.go
> +		l.queue.Remove(item)
Исправил

2022-12-25 18:59 UTC, Nikscorp approved these changes
Теперь все отлично, повышаю балл до максимального!

2022-12-25 19:29 UTC, merged